sudo: required
services: 
  - docker

before_install:
  - docker build -t docker-multi -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true docker-multi npm run test -- --coverage

after_success:
  - docker build -t blee1979/multi-client ./client
  - docker build -t blee1979/multi-server ./server
  - docker build -t blee1979/multi-ngnix ./ngnix
  - docker build -t blee1979/multi-worker ./worker
#log in to the docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin

#Take those images and push them to docker hub
  - docker push blee1979/multi-client 
  - docker push blee1979/multi-server 
  - docker push blee1979/multi-ngnix 
  - docker push blee1979/multi-worker 

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "Multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-605216531761"
  build_path: "Multi-docker"
  on:
    branch: master